allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

val newBuildDir: Directory =
    rootProject.layout.buildDirectory
        .dir("../../build")
        .get()
rootProject.layout.buildDirectory.value(newBuildDir)

subprojects {
    val newSubprojectBuildDir: Directory = newBuildDir.dir(project.name)
    project.layout.buildDirectory.value(newSubprojectBuildDir)
}
subprojects {
    project.evaluationDependsOn(":app")
}

// flutter_stripe's stripe_android compiles Kotlin at the JDK-21 toolchain default while
// Flutter pins Java to 17; Gradle rejects the inconsistency ("Inconsistent JVM-target").
// Force every subproject's Kotlin compilation to JVM 17 to match the Java target.
//
// Except the plugins that pin both their Java and their Kotlin to 1.8 in their
// own build file: forcing only the Kotlin half to 17 is exactly what would make
// them inconsistent. flutter_webrtc cannot be upgraded out of it (livekit_client
// pins it to 1.6.0). Re-check this list when adding a plugin: grep its
// android/build.gradle for VERSION_1_8.
val pinnedToJava8 = setOf(
    "flutter_callkit_incoming",
    "flutter_secure_storage",
    "flutter_webrtc",
    "geolocator_android",
    "livekit_client",
)
subprojects {
    if (name in pinnedToJava8) return@subprojects
    tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
        }
    }
}

// flutter_stripe's Android module is generated by syncing Stripe's React Native SDK,
// and the sync leaves one React-Native-only file behind: NativeStripeSdkModuleSpec
// .java, importing com.facebook.react.common.build.ReactBuildConfig. The plugin
// declares no React Native dependency but compiles src/main/kotlin as a Java source
// dir, so that file is compiled and the release build fails with "package
// com.facebook.react.common.build does not exist".
//
// Present in stripe_android 13.1.0, 14.0.0 and 14.0.1, so there is no version to
// move to; and StripeSdkModule.kt extends the generated spec, so it cannot be
// excluded either. Feed the module a two-constant stub instead (see
// android/rn-shim). Added to the Java compile task rather than the AGP source set
// so this needs no AGP types on the root buildscript classpath.
//
// DELETE both this block and android/rn-shim once flutter_stripe stops shipping
// the React Native spec file.
subprojects {
    if (name == "stripe_android") {
        tasks.withType<JavaCompile>().configureEach {
            source(rootProject.file("rn-shim"))
        }
    }
}

tasks.register<Delete>("clean") {
    delete(rootProject.layout.buildDirectory)
}
